# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ORGONOMY NOTES - Thoughts and experiments of Leonardo Amico
email: leonardo.amico@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Hi, I'm Leonardo Amico, a designer and technologist. Here is where I write about small experiments and quick thoughts.
baseurl: "/notes" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: orgonomyprod
github_username:  amicoleo

# Build settings
markdown: kramdown
theme: minima

#Paginate
gem: [jekyll-paginate]
paginate: 5
paginate_path: "/page:num/"

#Analytics
google_analytics: UA-84210001-1
